<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:DejaVu Sans,sans-serif;font-size:10px;color:#202938}h1{font-size:20px}h2{font-size:14px;border-bottom:1px solid #999;padding-bottom:3px;margin-top:18px}table{width:100%;border-collapse:collapse}th,td{padding:4px;border-bottom:1px solid #ddd;text-align:left;vertical-align:top}.muted{color:#666}.page-break{page-break-before:always}</style></head><body>
<h1>TheraConnect Longitudinal Patient Record</h1><p class="muted">Generated {{ now()->format('M d, Y h:i A') }} · Confidential clinical information</p>
<h2>Patient Profile</h2><table><tr><th>Name</th><td>{{ $patient->user->name }}</td><th>Email</th><td>{{ $patient->user->email }}</td></tr><tr><th>Date of birth</th><td>{{ $patient->date_of_birth?->format('M d, Y') ?? 'Not recorded' }}</td><th>Contact</th><td>{{ $patient->contact_no ?? 'Not recorded' }}</td></tr><tr><th>Address</th><td colspan="3">{{ $patient->address ?? 'Not recorded' }}</td></tr><tr><th>Personal issues</th><td colspan="3">{{ $patient->personal_issues ?? 'Not recorded' }}</td></tr><tr><th>Intake notes</th><td colspan="3">{{ $patient->notes ?? 'Not recorded' }}</td></tr></table>
<h2>Assigned Clinicians</h2><ul>@forelse($patient->assignedClinicians as $clinician)<li>{{ $clinician->user->name }}</li>@empty<li>None recorded</li>@endforelse</ul>
<h2>Appointments</h2><table><tr><th>Date</th><th>Clinician</th><th>Mode / Status</th><th>Reason</th><th>Clinic notes</th></tr>@forelse($patient->appointments->sortByDesc('scheduled_at') as $item)<tr><td>{{ $item->scheduled_at?->format('M d, Y h:i A') ?? 'Unscheduled' }}</td><td>{{ $item->clinician?->user?->name }}</td><td>{{ ucfirst($item->mode) }} / {{ ucfirst($item->status) }}</td><td>{{ $item->reason }}</td><td>{{ $item->clinic_notes }}</td></tr>@empty<tr><td colspan="5">No appointments</td></tr>@endforelse</table>
<h2>Assessments</h2><table><tr><th>Date</th><th>Instrument</th><th>Status</th><th>Score</th><th>Responses</th></tr>@forelse($patient->assessments->sortByDesc('created_at') as $item)<tr><td>{{ $item->completed_at?->format('M d, Y') ?? $item->created_at->format('M d, Y') }}</td><td>{{ $item->title() }}</td><td>{{ ucfirst($item->status) }}</td><td>{{ $item->score ?? '-' }}</td><td>{{ collect($item->responses ?? [])->map(fn($v,$k) => $k.': '.$v)->implode('; ') }}</td></tr>@empty<tr><td colspan="5">No assessments</td></tr>@endforelse</table>
<h2>Goals</h2>@forelse($patient->therapyGoals as $goal)<p><strong>{{ $goal->description }}</strong> ({{ ucfirst($goal->status) }})<br>Target: {{ $goal->target_date?->format('M d, Y') ?? 'None' }}; Ratings: {{ $goal->ratings->map(fn($r) => $r->rating.' on '.$r->created_at->format('M d, Y'))->implode(', ') ?: 'None' }}</p>@empty<p>None recorded</p>@endforelse
<h2>Assignments and Submissions</h2>@forelse($patient->assignments as $assignment)<p><strong>{{ $assignment->title }}</strong> · Due {{ $assignment->due_date?->format('M d, Y') ?? 'not set' }}<br>{{ $assignment->description }}<br>Worksheet: {{ $assignment->attachment_name ?? 'None' }}@foreach($assignment->submissions as $submission)<br>Submission {{ $submission->submitted_at?->format('M d, Y h:i A') }}: {{ $submission->content ?: 'No text' }}; File: {{ $submission->original_name ?? 'None' }}@endforeach</p>@empty<p>None recorded</p>@endforelse
<h2>Mood Check-ins</h2><table><tr><th>Date</th><th>Mood</th><th>Note</th></tr>@forelse($patient->moodLogs->sortByDesc('logged_at') as $mood)<tr><td>{{ ($mood->logged_at ?? $mood->created_at)->format('M d, Y h:i A') }}</td><td>{{ $mood->mood ?? $mood->rating }}</td><td>{{ $mood->note }}</td></tr>@empty<tr><td colspan="3">No mood check-ins</td></tr>@endforelse</table>
<h2>Clinician Notes</h2><h3>Shared</h3>@forelse($patient->clinicianNotes->where('is_shared',true) as $note)<p><strong>{{ $note->title }}</strong> · {{ $note->clinician?->user?->name }}<br>{{ $note->body }}</p>@empty<p>None</p>@endforelse<h3>Private</h3>@forelse($patient->clinicianNotes->where('is_shared',false) as $note)<p><strong>{{ $note->title }}</strong> · {{ $note->clinician?->user?->name }}<br>{{ $note->body }}</p>@empty<p>None</p>@endforelse
</body></html>
